### ISSUE TITLE
Playback not working after connection failure

### ISSUE THREAD

**Issue by jakobkukla** [dkanada/gelli#10]
Hi,

First of all I wanted to say that I really enjoy this app. It makes switching over from my traditional setup (which included Phonograph) to Jellyfin really easy.

Nevertheless I encountered an issue when trying to playback files after a failed connection.

Steps to reproduce:

1. Login to a server with an ip that is only accessible inside a private network.
2. Disconnect from that network and open the app. You will be redirected to the login screen.
3. Connect to the same network and server again or try to connect to the same server via a public ip.
4. You will be able to login successfully but cannot play any titles.

I was able to reproduce this multiple times with my setup. The only fix I could come up with was to reinstall the app and login again. After that everything worked as expected again.

Thanks :)

**Comment by dkanada** [comment]
Playback will still stop when a network failure happens, but it should now be possible after starting playback again. Can you confirm this is the case?

**Comment by jakobkukla** [comment]
Thanks for the fix. I can't test it anytime soon since my jellyfin server is not up and running at the moment. Will do as soon as I can.

**Comment by jakobkukla** [comment]
Just tested it. Couldn't reproduce this issue anymore. Seems to work great now. Thanks :)
