### ISSUE TITLE
Android 11 media controls not working

### ISSUE THREAD

**Issue by Baswazz** [dkanada/gelli#105]
Installed the app from F-Driod 1.2.0 it is not showing the Android 11 media controls on my Pixel 4XL.
For Plex it is working for Gelli I have a separate notification.
![Screenshot2](https://user-images.githubusercontent.com/1690629/98970709-8837e100-2510-11eb-983f-d7d93e1527f4.jpg)
![Screenshot](https://user-images.githubusercontent.com/1690629/98970714-8a01a480-2510-11eb-9649-bdaddfeb4b1b.jpg)

**Comment by KristupasSavickas** [comment]
There's option to control this: `Settings -> Notification -> Classic Design`. If you want to use the new notification design it should be disabled. I think classic design is disabled by default on newer androids, you've probably accidentally toggled it before.

**Comment by Baswazz** [comment]
@KristupasSavickas Thanks for the quick reply it was indeed on classic design. Now it is working.
