### ISSUE TITLE
can't even log in...?

### ISSUE THREAD

**Issue by MMeirolas** [dkanada/gelli#113]
Hello

Installed Gelli from F-Droid.

Enter my Jellyfin username, password and the jellyfin server address.  ->  "Invalid login details"

Change server address to server name.  ->  "Invaöif login details"

Can somebody tell me why this is?

**Comment by dkanada** [comment]
Did you append `http://` or `https://` to the server address?

**Comment by raz0r21** [comment]
I got it to work finally with http://<ip>:<port> 

would be reeeally nice to have this info when launching the app to save people from pulling their hair wondering why it wont connect.

**Comment by MMeirolas** [comment]
Hello

Yes it was the https thing.
I had previously tried it with https but i put the port number behind.

So now it works. Thx a lot

**Comment by dkanada** [comment]
The latest version of the API client was fixed to include the `https://` prefix, so as soon as 10.7.0 gets released I'll update Gelli to solve this issue.
