### ISSUE TITLE
Gelli crashes on completing an album with only one track

### ISSUE THREAD

**Issue by itsthejoker** [dkanada/gelli#118]
When playing an album with one track in it, the song will complete and I'll hear the first blip of the start of the song again, then it will immediately crash and I get the following error: 

![Screenshot_20210110-131507.png](https://user-images.githubusercontent.com/5179553/104131698-192b0d00-5346-11eb-80ef-07408ea68b82.png)

Android version RP1A.201005.004.A1, Pixel 2 device.

**Comment by dkanada** [comment]
Can you try this on the latest release on GitHub? I was unable to reproduce the issue there.

**Comment by itsthejoker** [comment]
Will try and report back.

**Comment by itsthejoker** [comment]
Apologies for the delay; this does not appear to be happening anymore! Thanks!
