### ISSUE TITLE
Search should include Artists

### ISSUE THREAD

**Issue by bendardenne** [dkanada/gelli#12]
As discussed on reddit. 

Searching currently ignores artists.

There's a minor change needed in [jellyfin-apiclient-java](https://github.com/jellyfin/jellyfin-apiclient-java/pull/67/).

**Comment by dkanada** [comment]
I just pushed a new point release so the API client should be ready.

**Comment by bendardenne** [comment]
Thanks for the merge

**Comment by ksb749** [comment]
It seems like Gelli 1.3.2 wont let me search for artists, tried multiple searches because i thought there was an error with some danish characters Jellyfin server 10.7.7
