### ISSUE TITLE
Any chance of Subsonic support ?

### ISSUE THREAD

**Issue by IceWreck** [dkanada/gelli#120]
I know this is a long shot but doesn't hurt to ask.

The existing subsonic clients on android are buggy and not very polished. I tried this with Jellyfin and its great. But is there a chance that you could also implement the subsonic api for Gelli alongside Jellyfin ?

**Comment by dkanada** [comment]
I'm definitely not adding Subsonic support to Jellyfin but there is a shim to access Jellyfin with other Subsonic clients if that interests you at all.

**Comment by IceWreck** [comment]
> I'm definitely not adding Subsonic support to Gelli 

I expected as much but had to ask. 

> but there is a shim to access Jellyfin with other Subsonic clients if that interests you at all.

i was interested in the other way round. I'm perfectly happy with Navidrome on desktop but find Gelli better than Dsub and other subsonic clients.

Anyways, thanks for your time

**Comment by IceWreck** [comment]
> but there is a shim to access Jellyfin with other Subsonic clients if that interests you at all.

Actually this gave me an idea. I'm free next week and will try to make something like that but reverse so that I can connect to subsonic servers using Gelli.

**Comment by grravity** [comment]
@IceWreck
Why not make an app that can handle multiple sources?
Jellyfin, Subsonic, mpd/mopidy, etc?
Just out of curiosity. I see where you were coming from with Subsonic support, (which would allow for Airsonic). Personally I think it would be cool to have a FOSS app that can just handle multiple different services, negating the need to have 4 different apps installed lol.

**Comment by dkanada** [comment]
My solution to that has always been the inverse, find a server that works with any number of clients. Jellyfin has five or six different desktop clients, mobile apps, terminal apps, and shims to basically every other media server protocol that exists.

**Comment by grravity** [comment]
I'll have to look into shims, not too familiar with it.
Thank you

**Comment by seniorm0ment** [comment]
@dkanda is it possible to setup gelli in a way that I can also connect to something like Mopidy-Jellyfin to remote control the playback on another machine from my phone (say a raspberry pi for example).

If so, how exactly would I go about doing this? It would have to make a connection to mopidy-http, (or mpd if I setup the mopidy-mpd extension I believe).

I was having trouble understanding what you were suggesting above. Even if I wanted to connect to mopidy to stream the output to my phone using Gelli, Gelli only makes connections to Jellyfin, not mopidy.

So to remote control, or just connect to mopidy seems not possible currently. So I was just looking for clarity as to what you were suggesting.
