### ISSUE TITLE
"Shuffle all" in "songs" tab only shuffles the first ~100 tracks

### ISSUE THREAD

**Issue by kylekyleton** [dkanada/gelli#121]
Version 1.2.0

I'm trying to shuffle my entire music library. I go to the "songs" tab, click the "shuffle all" button at the top, and it only shuffles the tracks that are initially loaded in the song list -- looks like it's only 100 items.

Now, if I first scroll down through the list of songs, letting the app display more and more songs, these songs are then included in the pool of songs that get shuffled when I click "shuffle all".

The "Page Size" option in the settings seems to have no effect on this behavior.

**Comment by dkanada** [comment]
The latest version will always shuffle your entire library regardless of the sort method. Can you confirm this resolves your issue?
