### ISSUE TITLE
Now Playing doesn't show in search results

### ISSUE THREAD

**Issue by strugee** [dkanada/gelli#128]
The Now Playing indicator which shows the currently-playing track disappears when you tap the search icon and search for something. This is a problem when you search for something and start playing a track directly from the search results, as there's no visual feedback that the track has actually started playing - which is especially a problem with tracks that start off extremely quietly.

I'm on Gelli 1.2.1.

**Comment by dkanada** [comment]
That's a fair point, I could probably add it there for convenience.

**Comment by dkanada** [comment]
The latest update includes the playback slider in the search activity. Let me know if that doesn't satisfy the requirements of this issue and I can open it again though.
