### ISSUE TITLE
Unable to reach server at this address.

### ISSUE THREAD

**Issue by hamidout** [dkanada/gelli#132]
Installed Gelli v1.2.1 from F-droid. Jellyfin works fine for me, but Gelli doesn't. I tried the hostname of my server and the ip address but still nothing. All apps can use the internet fine.
![IMG_20210324_004345](https://user-images.githubusercontent.com/66022183/112233706-295f4280-8c3b-11eb-924a-04b641470915.jpg)

**Comment by dkanada** [comment]
Add `https://` or `http://` at the front to fix this. It's a UX problem that will be solved as soon as I switch to the new API client.

**Comment by hamidout** [comment]
thank you, that worked.
