### ISSUE TITLE
Support transcoding to OPUS

### ISSUE THREAD

**Issue by Extarys** [dkanada/gelli#133]
[Xiph](https://wiki.xiph.org/Opus_Recommended_Settings) suggest 64 to 128 kb/s for streaming purposes. The low bandwidth requirement for good quality music on the road should be a good argument on it's own to allow transcoding to Opus on Gelli. The open source nature of the codec is the second one :smile: 

**Note that I do not know if Jellyfin backend support transcoding music files to Opus from the API.**

Currently only MP3 and AAC is supported according to the UI. I would also suggest adding 64 and 96 kb/s to the maximum bitrate list.

**Comment by dkanada** [comment]
@nyanmisaka does the server support FLAC for audio as well or is that only a video feature? @Extarys unfortunately OPUS transcoding isn't supported at all yet, but it's definitely a good idea.

**Comment by Extarys** [comment]
@dkanada I understand, I hope OPUS will be supported soon on the server as IMO it's the future of mp3. Damn that thing is good.

**Comment by nyanmisaka** [comment]
> @nyanmisaka does the server support FLAC for audio as well or is that only a video feature?

I think transcoding to FLAC is feasible.

**Comment by sPOiDar** [comment]
Transcoding to FLAC would be horribly inefficient for anything that's not already lossless.

**Comment by Extarys** [comment]
My understanding is that Apple created that standard. So in 2050 it will still only support Apple codecs (AAC and ALAC I suppose :laughing: ) and popular closed one like AC3.

Ok so, I found an issue about something that looks similar (2018) for hls.js [here](https://github.com/video-dev/hls.js/issues/1713), soundcloud made a custom thing to support opus hls payload.

I understand that TV and Chromecast family of devices wouldn't use those as they are not compatible, but for most people simply using Jellyfin itself or a specialized music app for Jellyfin (Gelli, Finamp), we just want the best quality with a small bandwidth. Opus fit that on-the-go Spotify-like lifestyle 1000%.

I have no idea how the backend works, but maybe a custom transcoding profile meant for music player (it wouldn't interfere with TV, PS4/5, etc), or a custom endpoint or something? What confuses me is, AV1 and MKV for example aren't HLS compliant and yet it works in Jellyfin. Why can't we make Opus transcoding for music?

I am ignorant when it comes to Jellyfin and how they want it to work, maybe they are 100% right and I'm the one who should just convert his whole music library to opus for when I'm on the road - Oh thinking about it, playlists and likes are gonna be a nightmare :scream: 

(Woops this is in Gelli repo, sorry dkanada :heart: )
