### ISSUE TITLE
Playback notification not dismissible after clearing play queue

### ISSUE THREAD

**Issue by SightSpirit** [dkanada/gelli#137]
Since the last update or the one before it (1.2.0 or 1.2.1), clearing the queue has caused the (classic-style, not Android 11-style) system notification for Gelli playback controls to go blank and not dismissible. In order to get rid of it, I either have to start another song, pause it, and then dismiss the notification, or I have to force-stop the app through system settings.

I'm using Gelli 1.2.1 (through F-Droid) on a Pixel 2 XL with Android 11. Probably not relevant, but my server runs JF 10.7.2 on a Windows 10 host.

**Comment by dkanada** [comment]
This should be fixed on the 1.2.2 version, let me know if you still see it after you update.

**Comment by SightSpirit** [comment]
All good! Thanks for the fix!
