### ISSUE TITLE
Invalid login credentials

### ISSUE THREAD

**Issue by WnndGws** [dkanada/gelli#140]
I am able to log into Gelli v1.2.0 but **unable** to log into v1.2.1 and 1.2.2.

I have confirmed login details and url is correct. Only tricky thing could be a space being used in the password?

Device: Google Pixel 3a
OS: Android 11

**Comment by dkanada** [comment]
Is the space on either the beginning or the end of the password?

**Comment by WnndGws** [comment]
Yes it is.

I have avoided changing the password mainly out of laziness as I have
several devices logged in, but will if it will fix this issue.

**Comment by dkanada** [comment]
That would explain it, the inputs automatically trim any spaces on the ends of the password. I could technically remove that but I thought it might be better UX to account for possible unwanted whitespace. What do you think?

**Comment by strugee** [comment]
Why don't you just have it retry with the non-trimmed password if the trimmed version fails?

**Comment by WnndGws** [comment]
I'm what way is it better UX?

**Comment by dkanada** [comment]
It was a small check added by the person who made a PR with some changes to the login page. I didn't think much of it at the time. I kind of agree it's mostly useless though, so I disabled it in the latest release. @WnndGws can you confirm your space password works in the update?

**Comment by WnndGws** [comment]
It's working. Thanks for your help
