### ISSUE TITLE
Text editing cursor handle has extremely poor contrast on the login screen

### ISSUE THREAD

**Issue by strugee** [dkanada/gelli#142]
A picture is worth a thousand words:

![signal-2021-04-26-160322](https://user-images.githubusercontent.com/911174/116143353-0ba55300-a6a9-11eb-91e0-3740242e3e90.jpg)

I actually could have _sworn_ that a few minutes ago it didn't show up at all, but it's possible that I simply didn't see it (though I _was_ actively looking for it).

I'm on Gelli 1.2.2 installed through F-Droid on a Pixel 3a XL running Android 11. Note that the app seems to have been (partially?) reset, which is why I had to log in again - I'm not sure if this is because of revamped login code in Gelli or whether it encountered an error because Signal backups completely filled all my disk space, which happens to me frequently and causes all kinds of app crashes.

**Comment by masonh** [comment]
Same issue on fresh install v1.3.0 from f-droid.

**Comment by dkanada** [comment]
This issue should be resolved on the latest version, can anyone confirm?

**Comment by dkanada** [comment]
I'll consider it fine unless someone reports otherwise.

**Comment by masonh** [comment]
v1.3.1 just released on f-droid. Fix confirmed. :+1:
