### ISSUE TITLE
Category visibility change requires app restart

### ISSUE THREAD

**Issue by klongmore** [dkanada/gelli#153]
As title, if making a category not visible from the settings, the app needs a full restart for that change to take effect (ordering however works straight away).

Phone/Model: OnePlus 7T HD1900
OS: Oxygen OS 11.0.1.1.HD65AA

**Comment by gordyhike** [comment]
Also, which may be related, when changing theme to light, dark, black, the background in albums, artist etc falls to update unless the app is restarted.

**Comment by dkanada** [comment]
@klongmore this should also be fixed.

@gordyhike I managed to fix the theme change but primary and accent colors will still require a restart if you want to open a separate issue for that one. The cause is an extremely deprecated library I'm currently in the process of removing.

**Comment by dkanada** [comment]
I'll be tracking general issues with the theme in #167 for now.
