### ISSUE TITLE
Cannot download all of single playlist from 'playlists' view

### ISSUE THREAD

**Issue by klongmore** [dkanada/gelli#154]
As title, when viewing all playlists in the 'playlists' view, pressing the three dots on the side of a playlist does not show an option to download. However, when going into the individual playlist view, and pressing the three dots up the top right, downloading is an option.

Phone/Model: OnePlus 7T HD1900
OS: Oxygen OS 11.0.1.1.HD65AA

**Comment by dkanada** [comment]
@klongmore can you confirm this is fixed in the update I just pushed?

**Comment by klongmore** [comment]
Working, thanks so much
