### ISSUE TITLE
dark themes broken

### ISSUE THREAD

**Issue by rightsaidfred99** [dkanada/gelli#167]
Hi,

Latest update broke dark themes both dark and black. 

Text in a list is white and the background is white making the app unusable in dark mode. 

This only occurs in list mode, grid mode is ok

**Comment by dkanada** [comment]
If you set the theme and then restart the app, everything should be fine. Let me know if that doesn't work.

**Comment by rightsaidfred99** [comment]
Thanks, that worked! I had to force stop it as it was like this for days. Appreciate this app so much.
12 June 2021, 16:37 by ***@***.***:

**Comment by dkanada** [comment]
I will leave this open as a reminder to check the theme updates once I finish removing a certain deprecated library. That would be the proper solution, and should fix the restart requirement.

**Comment by bgaesslein** [comment]
Apparently this bug was introduced with 06c40d3733ea1623071e2ae79e7ad6fbfcba6a51 but I'm not sure how, exactly.
