### ISSUE TITLE
App becomes unusable under specific conditions

### ISSUE THREAD

**Issue by MitchellWT** [dkanada/gelli#187]
Hello,

So I've been experiencing an issue where the app becomes unusable when certain events occur.

The following steps can be done to reproduce the error:

- Open the application, press the icon to search for a song
- Type the song to search, wait for response
- Select song from search list, wait for song to play
- Press the home button, return to home screen
- Close application from the application drawer, the song playing should still be player in the above tray
- Open the application again, receive a stack trace on screen

This error was encountered on a phone running android 9.

Once the first stack trace is received the application will always spit this stack trace when pressing the search icon and/or selecting an album from the album section screen.

![screen-01](https://user-images.githubusercontent.com/60099557/133065718-c8fa3ffc-b6e2-4cf5-9767-adf141de9c34.png)
![screen-02](https://user-images.githubusercontent.com/60099557/133065742-70bae6d9-4fc3-4e59-84fa-5572f7b31b8c.png)
![screen-03](https://user-images.githubusercontent.com/60099557/133065746-56704945-6771-4e97-9a49-dabdd7d6dc59.png)
![screen-04](https://user-images.githubusercontent.com/60099557/133065754-17055089-4389-4df1-bd5f-5d4559abb7fd.png)

**Comment by dkanada** [comment]
Your changes look fine, but I haven't been able to reproduce the issue. What version of Android are you running?

**Comment by MitchellWT** [comment]
Android 9. 

The phone that I was using for testing was the Samsung S8 Edge. I'm not sure If the edge has an impact or not with this error, but I have had some issues in the past with support in other applications.
