### ISSUE TITLE
Pausing resets system music progress bar (Android 10+)

### ISSUE THREAD

**Issue by Wonderfall** [dkanada/gelli#2]
First of all I'm very impressed by your work! It shows so much potential. Now, I'm sure you might be already aware of this issue, but I'll submit it nonetheless.

**Description :**
As the title states, pausing a music in Gelli resets the system music progress bar (it goes back to 00:00, and I can't get it to "resync" unless I play another song).

**Versions impacted** : 0.8.0, master (45d4cb84b04ef746f2a6709291d0a16d971079e1)

**Android version** : 10

**Screenshots** :
[Pausing](https://user-images.githubusercontent.com/5507232/83802967-ff3c9400-a6ab-11ea-9b14-d45d96b3d2af.png)
[After pausing](https://user-images.githubusercontent.com/5507232/83802959-fba90d00-a6ab-11ea-96d7-18abbe09f8eb.png)

Hope it helps!

**Comment by Wonderfall** [comment]
Found [an attempted fix](https://github.com/kabouzeid/Phonograph/commit/071723a150df9fdc3017ad1e7c3df0d78b998ec5#diff-5bc0fa6b57a61af0ff14d4bdb1b52425) made for Phonograph. It does kinda work, however the progress bar does not reset when the current song if finished.

It seems this "bug" only affects Android 10.

**Comment by dkanada** [comment]
I was not aware because I'm still stuck on Oreo, so thanks for the bug report! I'm guessing it would require some tweaks in the notification service.

**Comment by Wonderfall** [comment]
I can confirm this is fixed in release 1.1.2. It's even looking perfect in Android 11 media controls.
