### ISSUE TITLE
App crashes on start after update to 1.3.3

### ISSUE THREAD

**Issue by SightSpirit** [dkanada/gelli#212]
I just updated to the latest version, 1.3.3, and Gelli just straight-up crashes whenever I try to open it. It doesn't even make it to the UI.

Completely clearing the app's storage fixed the problem, which is not ideal but better than having to downgrade again. My guess is that there's an incompatibility in the old version's storage that's not addressed when updating to the new version.

For the record, I am on a Pixel 5a with Android 12L.

**Comment by HerrHellmus** [comment]
For me, the same happened, with the same solution (thanks for mentioning).
I'm on a Samsung Galaxy S10e, running Android 12.

**Comment by abstractionmage** [comment]
Same with Samsung Galaxy Note 8 on Android 9. Thanks for the workaround btw

**Comment by iparr** [comment]
Ditto. Back in now. A reminder to anyone like me that:

> it needs http://(IP):(port) with no /  

[Thanks.](https://www.reddit.com/r/jellyfin/comments/n0xacb/gelli_cant_reach_my_active_jellyfin_server/)

**Comment by stevleibelt** [comment]
Same for me:

* Google Nexus 5 with [e os](https://doc.e.foundation/devices/hammerhead)
* Xiaomi Poco X 3 with [crdroid 7.12](https://crdroid.net/surya/7)

It was working fine before the update of the latest version.

When I remove all the app data (configuration for server, user and password), I am able to open the server but the app starts crashing after playing the second or third song.

Hope this information helps. Thanks for your work, gelli is great!

**Comment by dkanada** [comment]
@jakobkukla has found the issue and a fix should be released soon.
