### ISSUE TITLE
Empty screen when starting Gelli offline

### ISSUE THREAD

**Issue by abstractionmage** [dkanada/gelli#216]
When I start Gelli without it being able to access my Jellyfin server (e.g. when I have airplane mode on or I am not connected to my home network), instead of showing my downloaded songs, playlists etc. Gelli only gives me an empty screen (see image below).
I can still open the left sidebar by swiping from the top left corner to the right, but the buttons in it don't work.

I'm using a Samsung Galaxy Note 8 phone with Android 9.

![Screenshot_20220618-200606_Gelli](https://user-images.githubusercontent.com/37195767/174451545-09434899-65c5-40ad-96b2-475e5d7aa944.jpg)

**Comment by dkanada** [comment]
This would be a feature request since Gelli doesn't currently support true offline mode, only audio caching.
