### ISSUE TITLE
Sort options 

### ISSUE THREAD

**Issue by screwfaze** [dkanada/gelli#22]
Please add options to sort by date added. I'm sure there are also more sort options others would like maybe they can add here.

Thanks

**Comment by AndreCarvalho** [comment]
I see that sort by date was just added in 1.0.3. However, I personally always want this to be descending, meaning latest additions appear first. Adding an option to set the sort order would be great!

**Comment by dkanada** [comment]
Sort order has been added for the next release and date added has indeed been added previously.
