### ISSUE TITLE
Crash: llegalStateException: Animator has already started, cannot change it now!

### ISSUE THREAD

**Issue by bgaesslein** [dkanada/gelli#236]
This occasionally happens, usually when the app has been running (not playing) in the background for a bit and I switch back to Gelli and start the paused song.

This might be a bug in the original Phonograph codebase because I found pretty much the exact error on a different Phonograph fork:
https://github.com/chr56/Phonograph_Plus/issues/51

The owner mentions an issue with a "color-change animation in main player ui" and it was fixed there at some point so I might look into it and see if I can pinpoint the exact reason for this crash.

**Comment by chr56** [comment]
https://github.com/chr56/Phonograph_Plus/commit/623029a1ecdb2caea03340800125d549e568393f , and https://github.com/chr56/Phonograph_Plus/commit/b6701819005ab7dc4a9eddb83f86d41948a9246d might be helpful.

623029a: cancel the previous one before (next) start
b670181: use fragment's lifecycle to not return `animateColorChange()` early if fragment state is _not at least_ `RESUMED`

@dkanada

**Comment by chr56** [comment]
However, if you implement `b670181`, there would be another bug -- color not changed if fragment is not `RESUMED`

So, the best practice is implement fully MVVM arch:
1. use observable data structure (`LiveData`/`StateFlow` in Kotlin Coroutine) on `PaletteColor`
2. observe it, if it changes then call `animateColorChange`
3. cancel the previous animator before next.
4. use fragment `Lifecycle`'s `repeatOnLifecycle(Lifecycle.State.STARTED)` to make sure running callback _only after_ fragment is STARTED. Notice that `repeatOnLifecycle` is a kotlin _suspend_ function (require Kotlin Coroutine and [lifecycle-ktx](https://developer.android.com/kotlin/ktx#lifecycle))!

However, **introduce kotlin is too costly to this project**, isn't it?

My ~Bad~ Example: https://github.com/chr56/Phonograph_Plus/commit/5ebcca330e00f06bbaa11a0f2aae5530bb775bb5
