### ISSUE TITLE
[Question] Use of Kotlin in the codebase ?

### ISSUE THREAD

**Issue by Ombrelin** [dkanada/gelli#242]
I'd like to offer contributions to the app, but I'd prefer to do it in Kotlin.
Would it be acceptable to you or not ?

**Comment by dkanada** [comment]
No issues here! If you could avoid refactoring existing code that would be great though.

**Comment by dkanada** [comment]
No issues here! If you could avoid refactoring code unless required that would be appreciated though.

**Comment by Ombrelin** [comment]
Okay noted, great thanks !
