### ISSUE TITLE
No playlists

### ISSUE THREAD

**Issue by meonkeys** [dkanada/gelli#245]
I'm suddenly not seeing any playlists in Gelli. I think this is due to an upstream bug in Jellyfin v10.8.11:

https://github.com/jellyfin/jellyfin/issues/10272

I'm entering the issue here just for tracking / posterity.

**Comment by mihawk90** [comment]
According to the last comment, this should now be fixed in .12?

**Comment by meonkeys** [comment]
Should be, yes, I just haven't had the chance to test it. Have you?

**Comment by mihawk90** [comment]
No, since my setup is based on the Linuxserver.io docker and it wasn't updated yet (also don't use playlists but it's not like I couldn't create one).

Just wanted to make sure this issue doesn't stay open forever :)

**Comment by meonkeys** [comment]
No worries, I tried it. Seems to work.
