### ISSUE TITLE
How to play an album with songs in the normal order?

### ISSUE THREAD

**Issue by AndreCarvalho** [dkanada/gelli#25]
Hi,  when I start playing an album the play queue displays the songs in a non sequential orde

**Comment by dkanada** [comment]
This is a duplicate of #11 so please track progress from there.

**Comment by dkanada** [comment]
Unless you're talking about the shuffle feature? In which case, you can fix the order by turning off shuffle from the now playing screen.

**Comment by AndreCarvalho** [comment]
Re-installing the app seems to have fixed this. Thanks
