### ISSUE TITLE
Missing images, that are on the server

### ISSUE THREAD

**Issue by andra5** [dkanada/gelli#30]
Hi
there's a bug, that consistently some cover photos don't appear (it's always the same ones), that do on the server.
https://imgur.com/a/TsGw5x9

**Comment by ThibaultNocchi** [comment]
Hello,
I'd like to add my vote on this. On my side, I got no cover art at all. I don't know if I'm doing something wrong or not.
Thanks dkanada for the app still!

**Comment by andra5** [comment]
unfortunately the bug persists for me, being on the same network, on every release. Not sure what i can post here to help...

**Comment by dkanada** [comment]
@ThibaultNocchi what version of Android are you running?

**Comment by andra5** [comment]
android 9 (coloros 6)

**Comment by ThibaultNocchi** [comment]
@dkanada  8.0.0

**Comment by dkanada** [comment]
This might have been fixed in recent updates, have you noticed it recently?

**Comment by ThibaultNocchi** [comment]
I haven't seen the problem for a while now, thanks! :)
