### ISSUE TITLE
Playlist/queue doesn't show the artist

### ISSUE THREAD

**Issue by Nickbert7** [dkanada/gelli#32]
The current playlist/queue  doesn't show the artist, just the album
![Screenshot_20200706-171609_Gelli](https://user-images.githubusercontent.com/14938497/86609672-88e1c900-bfac-11ea-84ac-acd418e623c7.png)

**Comment by Fabeuss** [comment]
[https://github.com/dkanada/gelli/issues/19](url)

**Comment by dkanada** [comment]
I'll close this as a duplicate so it can be tracked in the other issue.
