### ISSUE TITLE
Fdroid

### ISSUE THREAD

**Issue by gonjat** [dkanada/gelli#33]
I can't seem to locate info on how to download from Fdroid. I search fdroid and it's not there. Any help would be appreciated. Great work.

**Comment by ThibaultNocchi** [comment]
The PR to add the app was merged 4 days ago. You may need to force refresh the repo in Fdroid by pulling down, here is a link to it: https://f-droid.org/fr/packages/com.dkanada.gramophone/

**Comment by dkanada** [comment]
@ThibaultNocchi I hadn't noticed the submission finally went through, thanks!

**Comment by gonjat** [comment]
I was under a similar impression to dkanada, thinking it may not have been merged. I opened Fdroid this morn and it was there with out a manual refresh, I guess I was just impatient lol. Regardless I love this app! I'm hoping for chromecast next.
