### ISSUE TITLE
Option to login with selfsigned certificate

### ISSUE THREAD

**Issue by MakisChristou** [dkanada/gelli#36]
ATM I can't login to my Jellyfin instance since the https certificate is selfsigned. An option to trust said certificate would be nice because at the moment I can't use Gelli when away from home.

**Comment by MakisChristou** [comment]
Hi. Thanks for the response. The rationale for me is the fact that Let's Encrypt certificates don't work on bare IP addresses as far as I know, and some of us (at least me) don't use domain names for our Jellyfin servers. It would also be nice to be able to quickly test the app before buying and pointing any kind of domain name to your IP.

**Comment by ThibaultNocchi** [comment]
Oh yeah I forgot this, my bad. You're right Let's Encrypt doesn't provide for bare IPs.

I didn't understand your last sentence, sorry.

**Comment by MakisChristou** [comment]
What I wanted to say in the last sentence is the fact that even if someone is planning to use a domain name and a Let's Encrypt certificate, it would be nice to be able to play around and test the app with a self signed certificate outside of your local network without having to use http only.

**Comment by ThibaultNocchi** [comment]
Oh yeah you are right. Do you have examples of other Android apps that have the same feature? Having an example of how others implement it could help your case.

**Comment by MakisChristou** [comment]
Yes. The [nextcloud android app](https://play.google.com/store/apps/details?id=com.nextcloud.client&hl=en_US) uses a pop up that asks if you want to trust X certificate in order to proceed

**Comment by opeeba** [comment]
@MakisChristou I have successfully used [zerossl](https://zerossl.com/) for bare IP addresses.

**Comment by MakisChristou** [comment]
@opeeba Thanks! I had no idea. I will look into it.

**Comment by dkanada** [comment]
This should be working in the latest update, can anyone confirm?

**Comment by verahawk** [comment]
@dkanada I can confirm that Gelli 1.2.0 (from F-Droid) now works with self-signed certificate. Thank you 
very much for this functionality!

**Comment by dkanada** [comment]
Has anyone tried with HTTP recently? That should also be working but I haven't tested it personally.

**Comment by ThibaultNocchi** [comment]
Logging in over HTTP on the default JF port works.
