### ISSUE TITLE
Favorites tab/categories

### ISSUE THREAD

**Issue by kazukyakayashi** [dkanada/gelli#37]
There are all the tabs/categories except the favorites.
Is it possible that the songs marked as favorites on jellyfin are also marked as favorites in Gelli ?

**Comment by csolisr** [comment]
As an alternative, is it possible to show them as a default playlist in the Playlist tab?

**Comment by dkanada** [comment]
I don't like the idea of default playlists, I believe that should be handled by the server or plugins like the new smart playlist one that was released. If this did show up, it would probably be either a separate tab or an optional filter on the existing tabs. I would also include unplayed along with other filters, ideas are welcome.

**Comment by csolisr** [comment]
I'd vote for a separate tab in the meanwhile for easy access, and maybe adding a filter later.

**Comment by digitalentity** [comment]
I'd like to see a separate tab with favorites as well

**Comment by luuknieuwdorp** [comment]
I implemented the separate tab idea in #117. Feedback/requested changes are welcomed.

**Comment by a-rekkusu** [comment]
Is it possible to implement this for whole albums too? I'm more of an whole-album listener and only mark complete albums as favorite. None of those are getting shown in the Favorites tab though, because of this. It would be awesome if one could have the same view as in the Albums tab on Favorites. Maybe with a toggle for song/album view or so.

**Comment by luuknieuwdorp** [comment]
> 
> 
> Is it possible to implement this for whole albums too? I'm more of an whole-album listener and only mark complete albums as favorite. None of those are getting shown in the Favorites tab though, because of this. It would be awesome if one could have the same view as in the Albums tab on Favorites. Maybe with a toggle for song/album view or so.

As far as I can tell (not too familiar with the upstream API), albums don't seem to be able to be marked as favorite. You could hypothetically categorize it as such by checking if every item in an album is marked as favorite, but this would add a lot of complexity on the client side. My guess is you'll have a better time requesting this feature in the parent project, after which it could maybe be added here.

**Comment by a-rekkusu** [comment]
@luuknieuwdorp At least in the web clients I use this feature all the time - there is a heart icon on the album level, and for individual songs. The album then appears under Favorites and there under Albums. So the information should be there on the server side. I don't know how/if that info is accessible through the API Gelli is using though.

**Comment by dkanada** [comment]
It's entirely a client issue. Abums and artists need more options in Gelli but I haven't had the time to add them yet.

**Comment by a-rekkusu** [comment]
@dkanada thanks for clarifying. No worries, the work on this app is much appreciated. Would you like me to open a separate feature request ticket for this matter?

**Comment by dkanada** [comment]
yeah that sounds fine :)
