### ISSUE TITLE
Playlists Do Not Respect "Maximum List Size" Setting

### ISSUE THREAD

**Issue by omniusaspirer** [dkanada/gelli#42]
Per the title- regardless of what selection is made with this setting only 100 items are rendered.

**Comment by NovaCyntax** [comment]
This is probably the single-largest issue keeping me from using this app at the moment as well, hopefully it gets fixed because it seems simple enough and everything else works great for my use.

**Comment by rexbron** [comment]
See Known Issues in the main page

**Comment by mikikuri** [comment]
Had a look as I was troubled by this as well, and it seems like line 22 of PlaylistUtil.java may have been missed when implementing the new MaximumListSize() option.

Updating the query.setLimit() parameters to match the one found in other places like AlbumsFragment.java seem to fix the issue for me.

Location: app/src/main/java/com/dkanada/gramophone/util/PlaylistUtil.java
Line 22: query.setLimit(100);
New Line 22: query.setLimit(PreferenceUtil.getInstance(App.getInstance()).getMaximumListSize());

Of course this is coming from someone who doesn't really code, so implementing this might break something else, but atleast it seems to work for me.

![Screenshot_20200811-110115_Gelli](https://user-images.githubusercontent.com/67615080/89845936-34d98e00-dbc3-11ea-82ea-c65a079e2a7c.jpg)

**Comment by ZachMyers3** [comment]
Is there any update on this? It appears no matter what setting I tweak I can't get my maximum playlist size greater than 100.

**Comment by ZachMyers3** [comment]
Looking into this more (I'm by no means an Android developer) [this](https://github.com/dkanada/gelli/blob/82997e97c91fb0f5077ea139fac46d9306e22cef/app/src/main/java/com/dkanada/gramophone/util/PlaylistUtil.java#L22) does show that it has a hard limit of 100.

I'll try and look into changing this to the best of my ability.

**Comment by ZachMyers3** [comment]
Can we mark this closed now that that is merged @dkanada?
