### ISSUE TITLE
Setting the image cache size to "unlimited" crashes the app.

### ISSUE THREAD

**Issue by actuallynotjohndoe** [dkanada/gelli#47]
Setting the image cache size limit to "unlimited" renders the app unlaunchable until you reset it from system settings. It basically crashes when you try to launch it.

**Client:**
- Version: 1.0.2 from f-droid

**Device:** 
- Xiaomi Mi A2 Lite
- OS: Android 10
- Build number: QKQ1.191002.002.V11.0.7.0.QDLMIXM
- Security patch level: June 2020.
- Webview: 83.0.4103.106

**Server:**
- OS: Debian GNU/Linux 10 (buster)
- Jellyfin version: 10.5.5
- Architecture: X64

**Steps to reproduce:**
1. Install the app from f-droid.
2. Connect to server.
3. Go to settings and set the image cache size to "unlimited".
4. Close the app and kill it.
5. Try to launch it.

**Comment by dkanada** [comment]
How much free space do you have on your phone?

**Comment by actuallynotjohndoe** [comment]
> How much free space do you have on your phone?
More than 20GB. The RAM has currently round about 1.3GB left free.

**Comment by CappielloAntonio** [comment]
In PrefereceUtil.java
`public final int getImagesCacheSize() {
        return Integer.parseInt(mPreferences.getString(IMAGES_CACHE_SIZE, "400000000"));
    }`

Can parse an Interger, while the "unlimited" value is a Long

**Comment by dkanada** [comment]
Hah, that would do the trick. Let's just use the maximum value for an integer then, I doubt we'd need more space than that.

**Comment by CappielloAntonio** [comment]
> Hah, that would do the trick. Let's just use the maximum value for an integer then, I doubt we'd need more space than that.

Yeah, this can be a solution for this problem, but it's not perfect. The max int we can use is 2147483647, only a little more than the 2GB limit. 
The ideal solution i think would be to update Glide library, and only then we could use a Long for the cache size

**Comment by dkanada** [comment]
That also sounds like a decent solution.

**Comment by actuallynotjohndoe** [comment]
I don't know if you still need the stacktrace, but just in case: 

> 
> E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.dkanada.gramophone.debug, PID: 31719
>     java.lang.NumberFormatException: For input string: "10000000000"
>         at java.lang.Integer.parseInt(Integer.java:618)
>         at java.lang.Integer.parseInt(Integer.java:650)
>         at com.dkanada.gramophone.util.PreferenceUtil.getImagesCacheSize(PreferenceUtil.java:125)
>         at com.dkanada.gramophone.glide.CustomGlideModule.applyOptions(CustomGlideModule.java:26)
>         at com.bumptech.glide.Glide.get(Glide.java:168)
>         at com.bumptech.glide.RequestManager.<init>(RequestManager.java:62)
>         at com.bumptech.glide.RequestManager.<init>(RequestManager.java:53)
>         at com.bumptech.glide.manager.RequestManagerRetriever.supportFragmentGet(RequestManagerRetriever.java:198)
>         at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:104)
>         at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:87)
>         at com.bumptech.glide.Glide.with(Glide.java:657)
>         at com.dkanada.gramophone.adapter.AlbumCoverPagerAdapter$AlbumCoverFragment.loadAlbumCover(AlbumCoverPagerAdapter.java:121)
>         at com.dkanada.gramophone.adapter.AlbumCoverPagerAdapter$AlbumCoverFragment.onViewCreated(AlbumCoverPagerAdapter.java:109)
>         at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:332)
>         at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
>         at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
>         at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
>         at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
>         at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
>         at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
>         at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
>         at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
>         at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
>         at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:489)
>         at com.dkanada.gramophone.misc.CustomFragmentStatePagerAdapter.finishUpdate(CustomFragmentStatePagerAdapter.java:171)
>         at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
>         at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
>         at androidx.viewpager.widget.ViewPager.setAdapter(ViewPager.java:540)
>         at com.dkanada.gramophone.ui.fragments.player.PlayerAlbumCoverFragment.updatePlayingQueue(PlayerAlbumCoverFragment.java:94)
>         at com.dkanada.gramophone.ui.fragments.player.PlayerAlbumCoverFragment.onServiceConnected(PlayerAlbumCoverFragment.java:80)
>         at com.dkanada.gramophone.ui.activities.base.AbsMusicServiceActivity.onServiceConnected(AbsMusicServiceActivity.java:92)
>         at com.dkanada.gramophone.ui.activities.base.AbsSlidingMusicPanelActivity.onServiceConnected(AbsSlidingMusicPanelActivity.java:114)
>         at com.dkanada.gramophone.ui.activities.MainActivity.onServiceConnected(MainActivity.java:224)
>         at com.dkanada.gramophone.ui.activities.base.AbsMusicServiceActivity$1.onServiceConnected(AbsMusicServiceActivity.java:38)
>         at com.dkanada.gramophone.helper.MusicPlayerRemote$ServiceBinder.onServiceConnected(MusicPlayerRemote.java:75)
>         at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1948)
>         at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1980)
>         at android.os.Handler.handleCallback(Handler.java:883)
>         at android.os.Handler.dispatchMessage(Handler.java:100)
>         at android.os.Looper.loop(Looper.java:214)
>         at android.app.ActivityThread.main(ActivityThread.java:7397)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
> Disconnected from the target VM, address: 'localhost:8601', transport: 'socket'
>

**Comment by dkanada** [comment]
This should be resolved in the latest version, let me know if that's not the case.
