### ISSUE TITLE
Gelli crash in landscape display with flat mode enabled

### ISSUE THREAD

**Issue by etieng** [dkanada/gelli#51]
Hello, this app look promising.
I found a bug where the app crashes if my display is in landscape mode : phone rotated or split screen mode.
I'm running LineageOS 17.1 Android Q
Would a logcat be usefull ?
Thanks for your work.

**Comment by CappielloAntonio** [comment]
Did you set the player in flat mode?

**Comment by etieng** [comment]
Yep you're right, I'm in **flat** mode.
In **card** mode it goes well in landscape.

**Comment by CappielloAntonio** [comment]
The bug should be fixed with this https://github.com/CappielloAntonio/gelli/commit/5bc33aed1f530cb236c8c97b4cc5ddae1ac8ef25

**Comment by dkanada** [comment]
@CappielloAntonio if you split your smaller bug fixes into separate pull requests I can get them merged much faster :) I could have merged the image cache fix and this crash fix instantly and then tagged a release to fix the crash but I won't have time to review the full login redesign until another day. Do you mind if I cherry pick those two soon and tag a release?

**Comment by CappielloAntonio** [comment]
@dkanada you are right, my bad. Do whatever you think is best, no problem at all :)

**Comment by dkanada** [comment]
@CappielloAntonio no worries! I'll probably just pull out those two changes while we figure out the new images and such in your main pull request.

**Comment by dkanada** [comment]
I believe this was fixed in the last update.
