### ISSUE TITLE
Changing sort filter for albums does not refresh the list

### ISSUE THREAD

**Issue by ylefebvre** [dkanada/gelli#6]
In the album list, if I go to change the sorting order, the list of albums does not refresh immediately. I saw that if I close the app and restart it, then the newly selected order is taken into consideration. This is not currently intuitive.

**Comment by dkanada** [comment]
Same issue here, I need to figure out a nice way to refresh the main fragments when certain items are clicked but haven't had the time. The same problem also applies to many playlist actions, mainly because I almost never use playlists in my libraries.

**Comment by dbogdanov** [comment]
Same issue.

**Comment by dkanada** [comment]
This has been fixed on the latest version.
