### ISSUE TITLE
[Feature request] Inverse sort

### ISSUE THREAD

**Issue by alexbcberio** [dkanada/gelli#65]
It would be great to be able invert the sorting of items, this could be implemented as a checkbox inside the "sort method" submenu.

With this you could get the latest added songs when sorting by "added" as currently the first items are the oldest.

---

Great app, I'm very happy with it as I don't have to sync anymore all my songs on the phone.

**Comment by CappielloAntonio** [comment]
There's already a [PR ](https://github.com/dkanada/gelli/pull/54) for this. But for what I understand priority is being given to more important changes, and then to smaller ones like this.

**Comment by dkanada** [comment]
@CappielloAntonio your PRs should be merged, just need to figure out in what order we should apply the changes. I'll comment over there.

**Comment by dkanada** [comment]
Will be included in the next release.
