### ISSUE TITLE
"Can't reach server" on new install

### ISSUE THREAD

**Issue by itsthejoker** [dkanada/gelli#68]
Hi, all! I installed Gelli from F-Droid to give it a try, and I can't seem to log in. I just get "can't reach server". The server address is copied and pasted from my browser -- the URL definitely works on its own, but I wonder if Gelli might be having some issues with my reverse proxy setup?

Here's what I'm putting in the server field: `https://jellyfin.{mywebsite}.com`

Traffic is routed through nginx -> server -> docker container. Web UI works fine (and chromecasting, for what it's worth) work fine, but that's pretty much all I ever use.

Jellyfin version: 10.6.2
Gelli version: 1.0.3
Phone: Google Pixel 2
Android version: 10
Build number: QQ3A.200705.002

**Comment by dkanada** [comment]
I have two confirmations that the latest stable works with Gelli so it sounds specific to your environment, not sure what the exact cause could be though.

**Comment by itsthejoker** [comment]
Well, damn. Is Gelli expecting a port number or anything in the server field? What exactly is it trying to get? Is there anything else that can raise that error?

**Comment by itsthejoker** [comment]
Resolved on reddit -- the issue is that I have / had a base url set for my server which changed the location of the login page. Closing issue!
