### ISSUE TITLE
Why does the application require storage permissions?

### ISSUE THREAD

**Issue by ylefebvre** [dkanada/gelli#7]
Why does the application require storage permissions? Is it to allow you to download tracks to local storage? Or to allow you to play locally stored music in addition to Jellyfin music? If neither of these, then not sure why it would need this permission.

**Comment by dkanada** [comment]
When I was removing permissions from Phonograph, I left this one alone because I really want to see some form of offline cachine or download support at some point. The exact implementation is somewhat uncertain though.

**Comment by Maxr1998** [comment]
If you only want to do caching, you can safely remove that permission. You can still write to Android-managed cache directories in internal storage or external storage (like [virtual] sdcards), you don't need full access to external storage for that.

**Comment by dkanada** [comment]
The internal cache directory would get wiped when the application is uninstalled, so at minimum I would like the option to use an external directory for the cache.

**Comment by Maxr1998** [comment]
Fair enough. Even though it might be cache, some people might prefer to keep that when uninstalling, yes.

**Comment by mintou** [comment]
can this issue be closed, or moved to a FAQ entry?

**Comment by dkanada** [comment]
That seems reasonable, since I'm actually using the external storage this permission is actually required. I might create a FAQ somewhere on the README in the future.
