### ISSUE TITLE
"Shuffle all" crashes

### ISSUE THREAD

**Issue by shortN0te** [dkanada/gelli#70]
When pressing "Shuffle all" the app is crashing.
Pressing shuffle on official android client works fine and in the web-ui too.

Latest available Version from F-Droid. 1.0.3
Android 9
77 GB and over 9000 files in the library (Maybe to much files?)

**Comment by gerroon** [comment]
Same issue with shuffling in songs view. I am on Android 9 as well.

**Comment by kidonsky** [comment]
Same here but only with the option on the up-right menu. 
But in the *Titles* tab I can select Shuffle without problem.

Version 1.1.0

**Comment by LeRaldo** [comment]
I am also experiencing an app crash when choosing "Shuffle All" from the top right menu. I also have a rather sizeable library at over 680GB.

Device: OnePlus 8 Pro
OS: Oxygen OS 11.IN11AA (Android 11)
Gelli Version: 1.1.2
Jellyfin Server Version: 10.6.4

**Comment by dkanada** [comment]
I resolved this by removing that button, since it can't work without some minor changes to the codebase. The one in the songs adapter should function, and seems like a good enough solution for the time being.

**Comment by LeRaldo** [comment]
Maybe I'm using it incorrectly, but using the 'shuffle all' button in the Songs section seems to put the same 100 or so songs (mostly from the same 3 or 4 albums) on the playlist every time, and it seems like it goes in the same or a very similar order. It's not useful as a shuffle function for me.

**Comment by dkanada** [comment]
It's terrible UX but that button loads the songs currently loaded in that list, which means if you sort by random, it will be a true random sort. Perhaps I should default to random sort to fix this issue for now.

**Comment by LeRaldo** [comment]
Ah, that makes sense. Thank you.
