### ISSUE TITLE
Playback state not reported to the Jellyfin server

### ISSUE THREAD

**Issue by KristupasSavickas** [dkanada/gelli#75]
It looks like Gelli doesn't report playback state/progress back to the Jellyfin server. My specific gripe with this is that plugins like Last.fm don't work with Gelli.

In the screenshot bellow both clients are playing, however there's missing metadata for Gelli:
![Screenshot_20200817_132017](https://user-images.githubusercontent.com/1362643/90385872-669f9880-e08c-11ea-87a3-6ca31e61162c.png)

**Comment by dkanada** [comment]
The latest version has basic playback reporting. There may be some minor issues, but since it at least exists now, I think this one can be closed in favor of new issues about specific things.

**Comment by KristupasSavickas** [comment]
Seems to work fine, didn't notice any bugs as of yet.

**Comment by carks32** [comment]
I'm sorry to revive this issue but is this actually fixed? I see on my last.fm page that I'm listening to something but it never gets registered with Gelli, while it does on the Jellyfin webui and android app.

**Comment by Derkades** [comment]
It works for me, both in the jellyfin dashboard and to last.fm

**Comment by carks32** [comment]
It seems that for me it doesn't look it ever [reports the finished](https://i.imgur.com/lGwaRDB.png) playing part, compared to the [normal jellyfin app](https://i.imgur.com/xy5kgHO.png).

**Comment by Derkades** [comment]
Ah you're right, it publishes Now Playing status but doesn't add it to the track history after playing
