### ISSUE TITLE
Plans to start supplying APK?

### ISSUE THREAD

**Issue by ylefebvre** [dkanada/gelli#8]
While I am glad someone posted a compiled version of this application in the Jellyfin github discussions, it would be great if you would provide compiled apk versions. This would make it simpler for folks to try it out and give you feedback. Or perhaps you don't feel like the app is mature enough yet to distribute as binaries, which I totally understand.

**Comment by dkanada** [comment]
I have no problems at all distributing the app, the merge request for F-Droid can be found [here](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6755) but has been stalled for a few weeks. I would also be interested in publishing binaries on GitHub if I ever set up a pipeline here for Azure.

**Comment by ylefebvre** [comment]
Cool. I'll keep an eye on that

**Comment by dkanada** [comment]
I just finished Azure builds so here's an [official tag](https://github.com/dkanada/gelli/releases/tag/v1.0.0) with debug and release versions. I'll leave the issue open until the F-Droid submission makes some progress.

**Comment by DJWhitegold** [comment]
> I just finished Azure builds so here's an [official tag](https://github.com/dkanada/gelli/releases/tag/v1.0.0) with debug and release versions. I'll leave the issue open until the F-Droid submission makes some progress.

Sweet, thanks for sharing!

**Comment by ylefebvre** [comment]
Awesome! Thanks for making the APKs available here for the moment.

**Comment by z3ntu** [comment]
Just a quick note for me: I've downloaded the app, logged in to my jellyfin server and everything just works! Everything's fast, nice to see something based on Phonograph :) I would find it nice if Phonograph was mentioned in the readme of this repository though

**Comment by dkanada** [comment]
@z3ntu I mention Phonograph in the second sentence though :sweat_smile:

**Comment by z3ntu** [comment]
:see_no_evil: Oops

**Comment by dkanada** [comment]
The F-Droid release is now live so I'll close the issue! Still haven't looked into Google Play but I'm considering it.
