### ISSUE TITLE
Login credentials gone when opening without internet connection

### ISSUE THREAD

**Issue by budimanjojo** [dkanada/gelli#83]
To reproduce:
1. Disconnect internet connection. 
2. Open Gelli
3. Login page shown

You have to put in your login information again. This is terrible because I set Gelli to auto launch in my car headunit. Sometimes my internet connection is not established yet and Gelli is no longer being able to recover itself even if I got my internet connection back.

**Comment by ThibaultNocchi** [comment]
How would you see it behaving in the instance where the connection is gone? To me it should display a message like "connection gone, would you retry or connect to a new server?" maybe?

**Comment by budimanjojo** [comment]
That should do it, but it will be better if it will try to reconnect once internet connection is back without pressing anything

**Comment by ThibaultNocchi** [comment]
Ok that could do it, like the popup just displays "reconnecting in 5" and then the two buttons? And even more, the app could just detect it is the phone which is offline and not the end server. So it could automatically try again when internet is back, I'm sure in android there are events for this.

Also, as the author is intending to add cache and offline sync, there'll be a need to ensure the app isn't logged out when internet or the server can't be reached.

**Comment by budimanjojo** [comment]
Thank you. That will be perfect 😄

**Comment by ThibaultNocchi** [comment]
I'm not saying it's coming soon, I'm not even sure I'll be able to do it, maybe that'll be the task of someone more knowledgeable of Android dev. But I'll look into it, and at least describing what you as a user think is best is already a step in the right direction. :)

**Comment by strugee** [comment]
This also appears to happen when the server is extremely slow to respond (for whatever reason).

**Comment by grravity** [comment]
I have this issue I believe as well, when swapping to mobile data it logs me out. Force closing the app then reopening seems to fix it, however sometimes I have to do that twice or so.

**Comment by dkanada** [comment]
This should technically be resolved with the SelectActivity in recent updates, although there is probably room for improvement. Do you mind if I close this since the feature itself was implemented?

**Comment by budimanjojo** [comment]
I haven't have the time to play with Gelli nowadays, but I will close this issue as you requested if you are sure it's fixed :)
