### ISSUE TITLE
Queue issues, wrong song plays

### ISSUE THREAD

**Issue by Harteex** [dkanada/gelli#85]
There appears to be some queue issues where sometimes songs do not play correctly or the correct song doesn't play. #11 was fixed, but this is slightly different. With queue I mean the "up next" list, I don't queue songs manually, I just play album by album.

Anyway, I started the app, and resumed the current play queue. After a while I changed albums by finding the new album and pressing the first song.

Then I got into the following state.

After the first song played, it started playing the next one (song 2). However, it still shows that it was playing the song 1.
And after song 2 was done, it just stopped there (the play button still showed pause).
If I restart the queue by pressing the first song in the queue, the same thing happens again, so the there's something wrong with queue state.

It doesn't help to find the album again and start the first song again, I have to restart the app. After a restart the same album works ok.

In the faulty state, I also tried pressing the first song in the album and then skipping a few songs with the play controls. It would correctly switch and play the right song. However, as fast as the a song played to end and changed to the next, it played that song again, and now suddenly the song listed as the next upcoming one is the current one...

The system which queues songs seems a bit fragile.

App version 1.10. Server version 10.6.2.
Any other information needed?

I'll update the issue if I find a good way to reproduce. It has happened a few times so far, but I don't know when it happens.

**Comment by Harteex** [comment]
Here's a video showing the behaviour when the error happens. To show the error more easily I created an album which is basically just saying the song title. https://www.youtube.com/watch?v=2mqLhZ7mbhU The volume is a bit low so turn it up if you don't hear anything.

**Comment by yotoprules** [comment]
I have a similr problem, except it's the opposite: it goes to the next song, looks like it's playing the next song in the playlist, however it plays the previous song again (for the second time). skipping to the next song then going to the previous song fixes it. it's done this twice today in the 40 minutes i used it.

**Comment by niftium** [comment]
> I have a similr problem, except it's the opposite: it goes to the next song, looks like it's playing the next song in the playlist, however it plays the previous song again (for the second time). skipping to the next song then going to the previous song fixes it. it's done this twice today in the 40 minutes i used it.

This is the exact same problem that I have with v1.2.  Seems to be either the first or second track of every album/playlist I play.  The next song/previous song trick fixes it for the rest of that album; I'm not sure if it reoccurs if I queue another album in the same session or not.  I've reverted to v1.1.2 and haven't seen the issue yet.

**Comment by dkanada** [comment]
I've been working on another update that will hopefully resolve most of these race conditions. I'm hoping to push it in the next week or so, but I need to make sure it doesn't introduce any new crashes first because it's the start of a huge overhaul for playback.

**Comment by Harteex** [comment]
I'm currently using 1.2.1 and I haven't seen this issue in a while now.

However, I've seen some related minor issues such as the lock screen notification showing the wrong song being played, see video: https://youtu.be/YHEFRqMPCns
In the video it displays playing "Only Love" on the lockscreen, while it's actually playing the next song, "This City". When it played through to the next song, it showed "This City" while it was actually playing "Patience", so still one song off.
This doesn't happen always, but sometimes.

Can anyone else in the thread confirm if your issue is still showing up or not?

**Comment by niftium** [comment]
I haven't seen the "wrong song is playing" issue since I installed 1.2.1.  I haven't noticed it on the lockscreen either, but I rarely use lockscreen controls, so I probably wouldn't notice it if I /did/ happen to me.  Outside of issue #130, 1.2.1 has been rock solid for me.

**Comment by Harteex** [comment]
As neither me nor niftium are having this problem anymore, it does look like it's fixed. So I'm closing the issue.
If anyone else still has problems, feel free to either re-open this or create a new issue.
