### ISSUE TITLE
Invalid login credentials

### ISSUE THREAD

**Issue by DJWhitegold** [dkanada/gelli#87]
Gelli v1.1.1, pixel 3a with android 10,  jellyfin v10.6.4.
Fresh install of 1.1.1 says invalid login details after submitting the correct details. Tried uninstall and another install, plus reset server. Still no luck. Uninstalled again and installed Gelli v1.1.0 and it works perfectly.

EDIT: using a really long password but never been an issue before.

**Comment by LordEvron** [comment]
Same here.. tested with android 6.0.1

**Comment by dkanada** [comment]
Have you tried resetting the app data after an update? I had to change the authentication storage, perhaps I didn't properly clear the old information.

**Comment by DJWhitegold** [comment]
Thank you, that worked for me.
It seems the prefix of both https:// and http:// are missing from this version.
Thanks for sharing!

**Comment by n-peugnet** [comment]
Then maybe the problem is the error message. In this case it could be `invalid server address` instead of `invalid login details`. I guess this could be done easily if android forms have some kind of validation feature.
