### ISSUE TITLE
Auto-pause during call

### ISSUE THREAD

**Issue by timonoj** [dkanada/gelli#90]
Hi! 

When I receive a call, I can hear the audio ducks during the ringtone of the incoming call...but music resumes at full blare right when the call is picked up. It should pause instead.

Can you look into this one?

Thanks!

**Comment by dkanada** [comment]
This should now be resolved. Have you seen this issue on a recent version?

**Comment by dkanada** [comment]
Anyone is free to comment again if they have this issue but I believe it has been resolved.
