### ISSUE TITLE
Unable to login in new version - Invalid login credentials

### ISSUE THREAD

**Issue by ylefebvre** [dkanada/gelli#91]
I just got upgraded to version 1.1.1 through F-Droid. When I restarted Gelli, I was presented with the login screen, even though I was already connected. When I try to enter my credentials, I just get a message saying Invalid login credentials. I validated through the web client that my password was correct. I deleted the app data and cache. But after that, I still can't login. Any ideas on what else to do?

**Comment by ylefebvre** [comment]
I have also checked that I can login with the official Jellyfin client and that works correctly as well.

**Comment by dkanada** [comment]
#87

**Comment by ylefebvre** [comment]
Ah, sorry. Don't use GitHub much. Did not think to check the closed issues.

**Comment by dkanada** [comment]
no worries
