### ISSUE TITLE
1.1.2 does not show songs, albums, and artists

### ISSUE THREAD

**Issue by fgaz** [dkanada/gelli#99]
For me 1.1.2 from f-droid logs in correctly but does not show songs, albums, nor artists (collections and playlists are shown, but appear empty). I tried deleting the app data and the problem persists. 1.1.1 works fine.

I can provide you a temporary user on my jellyfin server if this issue cannot be reproduced with the one you use

**Comment by dkanada** [comment]
What version is your server?

**Comment by fgaz** [comment]
10.4.3

**Comment by dkanada** [comment]
Can you try it again on the latest version? That one is probably over a year old at this point.

**Comment by fgaz** [comment]
It should be at most 6 months old, which is the stable period for the distro I use. I'll try switching that package to unstable and will report back

**Comment by m0ngr31** [comment]
I have the same problem on server 10.5. It was working perfectly with older Gelli versions.

**Comment by dkanada** [comment]
Hmm @m0ngr31 did you have an issue open about this? I haven't seen it before.

**Comment by m0ngr31** [comment]
No, I just got around to coming to create an issue and I saw this one was already open.

**Comment by fgaz** [comment]
Just upgraded and yes, seems like <10.6 is incompatible with gelli 1.1.2

**Comment by dkanada** [comment]
I think I found the issue, this should be resolved in the next update.

**Comment by dkanada** [comment]
I'll close this since 1.2.0 should fix the issue, but feel free to open it again if the solution doesn't work.
